name: Build and deploy Node.js app to Azure Web App - ariaamsai2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ariaamsai2
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find package.json directory
        id: findpkg
        shell: bash
        run: |
          set -e
          FILE=$(git ls-files | grep -E '(^|/)package.json$' | head -n1 || true)
          if [ -z "$FILE" ]; then
            echo "No package.json found in repo"; exit 1
          fi
          DIR=$(dirname "$FILE")
          if [ "$DIR" = "." ]; then DIR="."; else DIR="./$DIR"; fi
          echo "Using package dir: $DIR"
          echo "dir=$DIR" >> $GITHUB_OUTPUT

      - name: Show detected directory contents
        run: ls -la
        working-directory: ${{ steps.findpkg.outputs.dir }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps, build, test
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
        working-directory: ${{ steps.findpkg.outputs.dir }}

      - name: Archive production artifacts
        shell: bash
        run: |
          APP_DIR="${{ steps.findpkg.outputs.dir }}"
          if [ -d "$APP_DIR/build" ]; then
            cd "$APP_DIR"
            zip -r ../build-artifact.zip build -x "*.git*"
          else
            cd "$APP_DIR"
            zip -r ../build-artifact.zip . -x "*.git*"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build-artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Unzip artifact
        run: unzip -o build-artifact.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C33BBA65DA2C40FFBB382F961043AE6C }}
          package: .
