name: Build and deploy Node.js app to Azure Web App - ariaamsai2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ariaamsai2
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node & npm versions
        run: |
          node -v || true
          npm -v || true

      - name: Find package.json directory
        id: findpkg
        shell: bash
        run: |
          FILE=$(git ls-files | grep -E '(^|/)package.json$' | head -n1 || true)
          echo "Found package.json at: $FILE"
          if [ -z "$FILE" ]; then
            echo "::error::No package.json found in repo"; exit 1
          fi
          DIR=$(dirname "$FILE")
          [ "$DIR" = "." ] && DIR="."
          echo "Using app dir: $DIR"
          echo "dir=$DIR" >> $GITHUB_OUTPUT

      - name: Show app dir contents
        run: |
          ls -la
          echo "----"
          ls -la ${{ steps.findpkg.outputs.dir }}
          echo "---- (one level deeper) ----"
          ls -la ${{ steps.findpkg.outputs.dir }}/.. || true

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies (with fallbacks)
        shell: bash
        working-directory: ${{ steps.findpkg.outputs.dir }}
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found -> npm ci --omit=dev"
            npm ci --omit=dev || INSTALL_FAIL=1
          else
            echo "No package-lock.json -> npm install --omit=dev"
            npm install --omit=dev || INSTALL_FAIL=1
          fi

          if [ "$INSTALL_FAIL" = "1" ]; then
            echo "Retrying install with --legacy-peer-deps..."
            if [ -f package-lock.json ]; then
              npm ci --omit=dev --legacy-peer-deps || exit 1
            else
              npm install --omit=dev --legacy-peer-deps || exit 1
            fi
          fi

      - name: Build (if present)
        working-directory: ${{ steps.findpkg.outputs.dir }}
        run: npm run build --if-present || true

      - name: Create deployment zip (ready-to-run source)
        shell: bash
        run: |
          APP_DIR="${{ steps.findpkg.outputs.dir }}"
          OUT="$GITHUB_WORKSPACE/app-ready.zip"
          rm -f "$OUT"
          cd "$APP_DIR"
          zip -r "$OUT" . -x "*.git*" "**/.github/**"
          echo "Created $OUT:"
          ls -lh "$OUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app-ready.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Verify artifact
        run: ls -la app-ready.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C33BBA65DA2C40FFBB382F961043AE6C }}
          package: app-ready.zip
