name: Build and deploy Node.js app to Azure Web App - ariaamsai2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ariaamsai2
  NODE_VERSION: '20'
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Find package.json directory
        id: findpkg
        shell: bash
        run: |
          FILE=$(git ls-files | grep -E '(^|/)package.json$' | head -n1 || true)
          echo "Found package.json at: $FILE"
          if [ -z "$FILE" ]; then
            echo "::error::No package.json found in repo"; exit 1
          fi
          DIR=$(dirname "$FILE")
          [ "$DIR" = "." ] && DIR="."
          echo "dir=$DIR" >> $GITHUB_OUTPUT
          echo "Using app dir: $DIR"

      - name: Show app dir contents
        run: |
          ls -la
          echo "----"
          ls -la ${{ steps.findpkg.outputs.dir }} || true

      - name: Install dependencies
        working-directory: ${{ steps.findpkg.outputs.dir }}
        run: npm ci || npm install

      - name: Build (if present)
        working-directory: ${{ steps.findpkg.outputs.dir }}
        run: npm run build --if-present || true

      - name: Determine deploy path
        id: pickpath
        shell: bash
        run: |
          APP_DIR="${{ steps.findpkg.outputs.dir }}"
          if [ -d "$APP_DIR/dist" ]; then
            echo "deploy_path=$APP_DIR/dist" >> $GITHUB_OUTPUT
          elif [ -d "$APP_DIR/build" ]; then
            echo "deploy_path=$APP_DIR/build" >> $GITHUB_OUTPUT
          else
            echo "deploy_path=$APP_DIR" >> $GITHUB_OUTPUT
          fi
          echo "Chosen deploy path: $(cat $GITHUB_OUTPUT | sed -n 's/.*deploy_path=//p')"

      - name: Create deployment zip
        shell: bash
        run: |
          DEPLOY_PATH="${{ steps.pickpath.outputs.deploy_path }}"
          OUT="$GITHUB_WORKSPACE/app.zip"
          rm -f "$OUT"
          cd "$DEPLOY_PATH"
          zip -r "$OUT" . -x "*.git*" "**/.github/**" "**/node_modules/**"
          ls -lh "$OUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Verify artifact
        run: ls -la app.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C33BBA65DA2C40FFBB382F961043AE6C }}
          package: app.zip

